filter:
    excluded_paths:
        - 'build/*'
        - 'build-ci/*'
        - 'example/*'
        - 'example-bench/*'
        - 'test/*'
        - 'vendor/*'

checks:
    php:
        return_doc_comments: true
        remove_extra_empty_lines: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
            before_parentheses:
                function_declaration: false
                closure_definition: false
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: false
                concatenation: true
                negation: false
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: false
                grouping: false
                function_call: false
                function_declaration: false
                if: false
                for: false
                while: false
                switch: false
                catch: false
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: false
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            if:
                opening: new-line
                always: false
                else_on_new_line: true
            for:
                opening: new-line
                always: true
            while:
                opening: new-line
                always: true
            do_while:
                opening: new-line
                always: true
                while_on_new_line: true
            switch:
                opening: new-line
            try:
                opening: new-line
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

tools:
    external_code_coverage:
        timeout: 1800
        runs: 1
    php_code_coverage: false